version: '3'
services:
  borgmatic:
    image: ghcr.io/pristavkin/docker-borgmatic-rclone:latest
    container_name: borgmatic
    hostname: ${HOSTNAME}
    volumes:
      - ${VOLUME_SOURCE}:/mnt/source:ro               # backup source
      - ${VOLUME_TARGET}:/mnt/borg-repository         # backup target
      - ${VOLUME_ETC_BORGMATIC}:/etc/borgmatic.d/     # borgmatic config file(s) + crontab.txt
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg      # config and keyfiles
      - ${VOLUME_RCLONE_CONFIG}:/root/.config/rclone/ # rclone config file(s)
      - ${VOLUME_SSH}:/root/.ssh                      # ssh key for remote repositories
      - ${VOLUME_BORGMATIC_STATE}:/root/.borgmatic    # borgmatic state files
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg        # checksums used for deduplication
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
      - RUN_ON_STARTUP=${RUN_ON_STARTUP}
